# Generated by Django 4.2.6 on 2023-10-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='class_counts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='detected_classes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='results', verbose_name='Result Image'),
        ),
    ]
